application: thelazygibbonapi
version: v0-0-18
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /admin
  static_dir: admin
  login: admin
  
- url: /web
  static_dir: web

- url: /.*
  script: tlg.app
  

  
libraries:
- name: jinja2
  version: latest